name: mlnote

dependencies:
  - ipython
  - python
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  - autograd
  - pytorch
  - tensorflow
  - jax
  - jinja2
  - openpyxl
  - pip
  - pip:
    - schemdraw
